/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("micronaut.microstream.grpc.java-library-conventions")
    id("io.micronaut.application")
    id("io.micronaut.docker") 
    id("com.github.johnrengelman.shadow") version "8.1.1"
    // version "4.1.1"
}

dependencies {
    runtimeOnly("org.yaml:snakeyaml")
    implementation(project(":jhub-grpc-stack"))
    implementation("org.projectlombok:lombok:1.18.28")

    runtimeOnly("ch.qos.logback:logback-classic")

    implementation("io.micronaut.microstream:micronaut-microstream")
    implementation("io.micronaut.microstream:micronaut-microstream-annotations")
    implementation("io.micronaut.microstream:micronaut-microstream-rest")

    implementation("io.micronaut:micronaut-management")
    implementation("io.micronaut.micrometer:micronaut-micrometer-core")
    implementation("io.micronaut.validation:micronaut-validation")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    implementation("io.micronaut:micronaut-discovery-core")
    implementation("io.micronaut.kubernetes:micronaut-kubernetes-discovery-client")
    
    implementation("io.grpc:grpc-services")
    implementation("io.micronaut.grpc:micronaut-grpc-runtime")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.15.2")
    implementation("io.micronaut.kafka:micronaut-kafka")

    testImplementation("org.junit.jupiter:junit-jupiter-params")
    testImplementation("io.micronaut:micronaut-http-client")
    
    annotationProcessor("io.micronaut:micronaut-management")
    annotationProcessor("io.micronaut.microstream:micronaut-microstream-annotations")
    annotationProcessor("io.micronaut.serde:micronaut-serde-processor")
    annotationProcessor("io.micronaut.validation:micronaut-validation-processor")
    annotationProcessor("org.projectlombok:lombok:1.18.28")
    annotationProcessor("io.micronaut.security:micronaut-security-annotations")
}

application{
    mainClass.set("orange.business.jhub.Application")
}

